### ISSUE TITLE
Evaluation of bconexus_uat_v1.6_021224

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/dnanexus#11]
There are a few items that could still be improved: 

- [x] Upload of BCO to public site (https://biocomputeobject.org) works fine but any other URL fails. I tried `http:localhost:8000` and `https://test.portal.biochemistry.gwu.edu/`.
- [x] Upon successful upload the only message is "File upload Succeeded". The response from the BCODB will contain the object id of the new BCO, and should be given to the user.

**Comment by kee007ney** [comment]
The new version looks good, just a couple minor things to mention:
- URL only works for biocomputeobject.org, so if someone wanted to to deposit to a different instance (e.g. the FDA instance), they wouldn't be able to.
- Would be good to tell the user what the object ID is after submission (instead of just "File upload succeeded.")
